name: flchain_extension
description: Flutter chainable widget extension library. Provides elegant widget modifiers, text styling, animations and more.
version: 0.0.4
homepage: https://github.com/lotawei/flchain_extension
repository: https://github.com/lotawei/flchain_extension
issue_tracker: https://github.com/lotawei/flchain_extension/issues
topics:
  - widget
  - extension
  - animation
  - ui

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
